[PHP]
; Error handling
display_errors = On
error_reporting = E_ALL

; Upload limits
upload_max_filesize = 64M
post_max_size = 64M

; Memory
memory_limit = 512M

; Execution time
max_execution_time = 300

; Timezone
date.timezone = UTC
